import type { Project } from '@/types/project'

export interface DeployToGitHubOptions {
  project: Project
  githubToken?: string
  githubUsername?: string
  repositoryName?: string
}

export interface DeployToGitHubResult {
  success: boolean
  url?: string
  repositoryUrl?: string
  error?: string
}

export async function deployToGitHub(
  options: DeployToGitHubOptions
): Promise<DeployToGitHubResult> {
  const { project, githubToken, githubUsername, repositoryName } = options

  if (!githubToken) {
    return {
      success: false,
      error: 'GitHub Personal Access Tokenが設定されていません。'
    }
  }

  if (!githubUsername) {
    return {
      success: false,
      error: 'GitHubユーザー名が設定されていません。'
    }
  }

  const repoName = repositoryName || project.name.toLowerCase().replace(/\s+/g, '-')

  try {
    // 1. Create repository
    const createRepoResponse = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${githubToken}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        name: repoName,
        description: `${project.name} - Generated by Readdy AI`,
        auto_init: false,
        private: false
      })
    })

    if (!createRepoResponse.ok) {
      const error = await createRepoResponse.json()
      // Repository already exists
      if (createRepoResponse.status === 422) {
        console.log('Repository already exists, will update it')
      } else {
        throw new Error(`Failed to create repository: ${error.message}`)
      }
    }

    // 2. Prepare files for GitHub Pages
    const files = prepareGitHubPagesFiles(project)

    // 3. Create gh-pages branch and push files
    const treeItems = Object.entries(files).map(([path, content]) => ({
      path,
      mode: '100644',
      type: 'blob',
      content
    }))

    // Create blobs
    const blobs = await Promise.all(
      treeItems.map(async (item) => {
        const blobResponse = await fetch(
          `https://api.github.com/repos/${githubUsername}/${repoName}/git/blobs`,
          {
            method: 'POST',
            headers: {
              'Authorization': `Bearer ${githubToken}`,
              'Accept': 'application/vnd.github.v3+json',
              'Content-Type': 'application/json'
            },
            body: JSON.stringify({
              content: item.content,
              encoding: 'utf-8'
            })
          }
        )
        const blob = await blobResponse.json()
        return {
          path: item.path,
          mode: item.mode,
          type: item.type,
          sha: blob.sha
        }
      })
    )

    // Create tree
    const treeResponse = await fetch(
      `https://api.github.com/repos/${githubUsername}/${repoName}/git/trees`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          tree: blobs
        })
      }
    )
    const tree = await treeResponse.json()

    // Create commit
    const commitResponse = await fetch(
      `https://api.github.com/repos/${githubUsername}/${repoName}/git/commits`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          message: 'Deploy to GitHub Pages',
          tree: tree.sha,
          parents: []
        })
      }
    )
    const commit = await commitResponse.json()

    // Create or update gh-pages branch
    const refResponse = await fetch(
      `https://api.github.com/repos/${githubUsername}/${repoName}/git/refs/heads/gh-pages`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          ref: 'refs/heads/gh-pages',
          sha: commit.sha
        })
      }
    )

    if (!refResponse.ok && refResponse.status !== 422) {
      // Try updating existing branch
      await fetch(
        `https://api.github.com/repos/${githubUsername}/${repoName}/git/refs/heads/gh-pages`,
        {
          method: 'PATCH',
          headers: {
            'Authorization': `Bearer ${githubToken}`,
            'Accept': 'application/vnd.github.v3+json',
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            sha: commit.sha,
            force: true
          })
        }
      )
    }

    // 4. Enable GitHub Pages
    await fetch(
      `https://api.github.com/repos/${githubUsername}/${repoName}/pages`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          source: {
            branch: 'gh-pages',
            path: '/'
          }
        })
      }
    )

    const pagesUrl = `https://${githubUsername}.github.io/${repoName}`
    const repositoryUrl = `https://github.com/${githubUsername}/${repoName}`

    return {
      success: true,
      url: pagesUrl,
      repositoryUrl
    }
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'デプロイに失敗しました'
    }
  }
}

function prepareGitHubPagesFiles(project: Project): Record<string, string> {
  const files: Record<string, string> = {}

  // Generate HTML for each page
  const pages = project.pages || []
  
  pages.forEach((page) => {
    const fileName = page.path === '/' ? 'index.html' : `${page.path.replace(/^\//, '')}.html`
    
    files[fileName] = `<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${page.metaTitle || project.name}</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
  <div id="root"></div>
  <script crossorigin src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
  <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
  <script type="text/babel">
    ${page.componentCode}
    
    const root = ReactDOM.createRoot(document.getElementById('root'));
    root.render(<App />);
  </script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
</body>
</html>`
  })

  // Add README
  files['README.md'] = `# ${project.name}

Generated by Readdy AI

## Pages

${pages.map(p => `- [${p.path}](${p.path === '/' ? 'index.html' : p.path.replace(/^\//, '') + '.html'})`).join('\n')}

## Deployment

Deployed using GitHub Pages.
`

  return files
}
