-- 開発用：RLSを無効化
-- 本番環境では認証機能を実装してRLSを有効化すること

ALTER TABLE projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE pages DISABLE ROW LEVEL SECURITY;
ALTER TABLE assets DISABLE ROW LEVEL SECURITY;
ALTER TABLE agents DISABLE ROW LEVEL SECURITY;
